### ISSUE TITLE
Create an openrefine-announce mailing list

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/openrefine.org#121]
The current OpenRefine blog is basically a giant black hole because there's no way to subscribe to it so posts which are important to the community, like the recent appointment of a new steering committee member, end up never getting seen. It would be worth considering establishing a low volume, post only, opt-in announcement mailing list that people can subscribe to.

**Comment by trnstlntk** [comment]
There's the OpenRefine newsletter which is run by Martin (at RefinePro).

Re: the Discourse forum: yes, a read-only topic to which people can subscribe sounds like an approach. That said, I notice the Discourse forum doesn't have community buy-in so I don't know if we should go ahead with it.

I will leave the project by end November 2022 so I leave it to others to decide what to do and take action. I suggest that people with strong opinions also do the work they think needs to be done. It seems we don't want overhead, so the community will have to do it, not paid staff.

**Comment by trnstlntk** [comment]
@magdmartin runs a newsletter via RefinePro, example: https://kb.refinepro.com/2022/05/openrefine-may-2022-review.html

**Comment by martinrefinepro** [comment]
the RefinePro newsletter should not be the reference point for the community since it is managed via a different organization. 

We publish a tweet for each blogpost on the OpenRefine twitter account. 
Usually, blogposts are also referenced on the mailing list. We should do the same with discourse 
Blogposts serve a different purpose and audience than a mailing list. I got feedback from several organizations and executives that only read the website and blog section. If important news is available only on a mailing list those are missed and OpenRefine is missing some partnership opportunities. 

the new discourse platform will help manage different channel, community announcement can be one of them.

**Comment by ostephens** [comment]
I've created a [News and Announcements category on the new forum](https://forum.openrefine.org/c/news)

You can get notifications by email (see the link @wetneb posted above) or subscribe to the RSS at https://forum.openrefine.org/c/news.rss

**Comment by wetneb** [comment]
This can probably be closed now that the announcement category was created?
I would intuitively keep the blog too.

**Comment by ostephens** [comment]
I think the [`News and announcements` category](https://forum.openrefine.org/c/news/13) is now working OK and automatically bringing stuff in from the blog. I've had to make some tweaks and did initially see some duplication so I'll keep an eye on it.

**Comment by wetneb** [comment]
I'm expecting there to be some duplication with the migration to the new website, because the structure of the feed has changed slightly unfortunately (but the feed address and the previous blog post URLs should redirect properly)

**Comment by ostephens** [comment]
Ah - maybe that was what caused it. I've already deleted the duplicate posts in the News and Announcements category

**Comment by wetneb** [comment]
Closing since the category is now up and running - please do reopen if you disagree
